// Generated by an LLM and not yet reviewed by a human.
import type { CommittedFiberChange } from "@react-record/devtools-api";
import { createSafeJsonReplacer, formatElementSummary, isElementLike } from "../../../utils/safe-json";

type HookChange = NonNullable<CommittedFiberChange["hooks"]>[number];

type ComponentWithHookChanges = CommittedFiberChange & {
  displayName: string;
  hooks: NonNullable<CommittedFiberChange["hooks"]>;
};

function isComponentWithHookChanges(
  component: CommittedFiberChange,
): component is ComponentWithHookChanges {
  return (
    component.displayName != null && component.hooks != null && component.hooks.length > 0
  );
}

function isFormattedElementSummaryString(value: unknown): value is string {
  return typeof value === "string" && value.startsWith("[HTMLElement ") && value.endsWith("]");
}

function formatValueForLLM(value: unknown): string {
  if (value === undefined) {
    return "undefined";
  }

  if (isFormattedElementSummaryString(value)) {
    return value;
  }

  if (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    value === null
  ) {
    return JSON.stringify(value);
  }

  if (isElementLike(value)) {
    return formatElementSummary(value);
  }

  const serialized = JSON.stringify(value, createSafeJsonReplacer());
  return serialized ?? String(value);
}

function formatHookLabel(hook: HookChange): string {
  const hookPath = "hookPath" in hook ? hook.hookPath : null;
  const hookName = "hookName" in hook ? hook.hookName : null;
  if (hookPath != null && hookPath.length > 0) {
    return `${hook.hookIndex} (${hookPath.join(" > ")})`;
  }
  if (hookName != null) {
    return `${hook.hookIndex} (${hookName})`;
  }
  return String(hook.hookIndex);
}

function formatCommitSection(changedComponents: ComponentWithHookChanges[]): string[] {
  const componentNames = new Set(changedComponents.map(({ displayName }) => displayName));
  const totalHookEvents = changedComponents.reduce((sum, { hooks }) => sum + hooks.length, 0);

  const lines: string[] = [
    `- Components with hook changes: ${componentNames.size}`,
    `- Hook change events: ${totalHookEvents}`,
  ];

  changedComponents.forEach(({ displayName, hooks }) => {
    hooks
      .slice()
      .sort((left, right) => left.hookIndex - right.hookIndex)
      .forEach((hook) => {
        lines.push(`- Component ${displayName}, Hook ${formatHookLabel(hook)}`);
        lines.push(`  - ${formatValueForLLM(hook.prev)} -> ${formatValueForLLM(hook.next)}`);
      });
  });

  return lines;
}

export function getCommitSectionLines(fiberChanges: CommittedFiberChange[]): string[] {
  const changedComponents = fiberChanges.filter(isComponentWithHookChanges);
  if (changedComponents.length === 0) {
    return [];
  }
  return formatCommitSection(changedComponents);
}
