// Generated by an LLM and not yet reviewed by a human.
import type { CommittedFiberChange } from "@react-record/devtools-api";
import { createSafeJsonReplacer, formatElementSummary, isElementLike } from "../../utils/safe-json";

type HookChange = NonNullable<CommittedFiberChange["hooks"]>[number];

type CommitEntry = {
  componentName: string;
  hookIndex: number;
  hookName?: string | null;
  hookPath?: Array<string> | null;
  prev: unknown;
  next: unknown;
};

function isFormattedElementSummaryString(value: unknown): value is string {
  return typeof value === "string" && value.startsWith("[HTMLElement ") && value.endsWith("]");
}

function formatValueForLLM(value: unknown): string {
  if (value === undefined) {
    return "undefined";
  }

  if (isFormattedElementSummaryString(value)) {
    return value;
  }

  if (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    value === null
  ) {
    return JSON.stringify(value);
  }

  if (isElementLike(value)) {
    return formatElementSummary(value);
  }

  const serialized = JSON.stringify(value, createSafeJsonReplacer());
  return serialized ?? String(value);
}

function buildCommitEntries(
  fiberChangesByCommit: CommittedFiberChange[][],
): Map<number, CommitEntry[]> {
  const entriesByCommit = new Map<number, CommitEntry[]>();

  fiberChangesByCommit.forEach((commitChanges, commitIndex) => {
    const nextEntries: CommitEntry[] = [];

    commitChanges.forEach(({ displayName, hooks }) => {
      if (displayName == null) {
        return;
      }

      if (hooks == null || hooks.length === 0) {
        return;
      }

      hooks
        .slice()
        .sort((left, right) => left.hookIndex - right.hookIndex)
        .forEach((hook: HookChange) => {
          nextEntries.push({
            componentName: displayName,
            hookIndex: hook.hookIndex,
            hookName: "hookName" in hook ? (hook.hookName ?? null) : null,
            hookPath: "hookPath" in hook ? (hook.hookPath ?? null) : null,
            prev: hook.prev,
            next: hook.next,
          });
        });
    });

    if (nextEntries.length > 0) {
      entriesByCommit.set(commitIndex, nextEntries);
    }
  });

  return entriesByCommit;
}

type FormatCommitHookChangedHistoryForLLMOptions = {
  extraSummaryLines?: string[];
};

export function formatCommitHookChangedHistoryForLLM(
  fiberChangesByCommit: CommittedFiberChange[][],
  options?: FormatCommitHookChangedHistoryForLLMOptions,
): string {
  const commitEntries = buildCommitEntries(fiberChangesByCommit);
  const commitIndices = Array.from(commitEntries.keys()).sort((left, right) => left - right);

  const lines = [
    "Commit-oriented hook change history summary",
    ...(options?.extraSummaryLines ?? []),
  ];

  if (commitIndices.length === 0) {
    return lines.join("\n");
  }

  commitIndices.forEach((commitIndex) => {
    const entries = commitEntries.get(commitIndex) ?? [];
    const components = new Set(entries.map(({ componentName }) => componentName));
    const commitNumber = commitIndex + 1;

    lines.push(
      "",
      `Commit ${commitNumber}`,
      `- Components with hook changes: ${components.size}`,
      `- Hook change events: ${entries.length}`,
    );

    entries.forEach(({ componentName, hookIndex, hookName, hookPath, prev, next }) => {
      const hookLabel =
        hookPath != null && hookPath.length > 0
          ? `${hookIndex} (${hookPath.join(" > ")})`
          : hookName != null
            ? `${hookIndex} (${hookName})`
            : String(hookIndex);

      lines.push(`- Component ${componentName}, Hook ${hookLabel}`);
      lines.push(`  - ${formatValueForLLM(prev)} -> ${formatValueForLLM(next)}`);
    });
  });

  return lines.join("\n");
}
