// Generated by an LLM and not yet reviewed by a human.
import type { CommittedFiberChange } from "@react-record/devtools-api";
import { buildRerenderCountLines } from "./util/build-rerender-count-lines";
import { getCommitSectionLines } from "./util/format-commit-section";

export function formatCommitHookChangedHistoryForLLM(
  fiberChangesByCommit: CommittedFiberChange[][],
): string {
  const lines = [
    "Commit-oriented hook change history summary",
    ...buildRerenderCountLines(fiberChangesByCommit),
  ];

  fiberChangesByCommit.forEach((fiberChanges, commitIndex) => {
    lines.push("", `Commit ${commitIndex + 1}`, ...getCommitSectionLines(fiberChanges));
  });

  return lines.join("\n");
}
