// Generated by an LLM and not yet reviewed by a human.
import type { CommittedFiberChange } from "@react-record/devtools-api";

export function buildRerenderCountLines(
  fiberChangesByCommit: CommittedFiberChange[][],
): string[] {
  const rerenderCounts = new Map<string, number>();

  for (const commitChanges of fiberChangesByCommit) {
    const rerenderedInCommit = new Set<string>();
    for (const change of commitChanges) {
      if (change.displayName == null) {
        continue;
      }
      if (change.isFirstMount) {
        continue;
      }
      rerenderedInCommit.add(change.displayName);
    }
    for (const componentName of rerenderedInCommit) {
      rerenderCounts.set(componentName, (rerenderCounts.get(componentName) ?? 0) + 1);
    }
  }

  if (rerenderCounts.size === 0) {
    return [];
  }

  const sorted = Array.from(rerenderCounts.entries()).sort(
    ([leftName, leftCount], [rightName, rightCount]) => {
      if (rightCount !== leftCount) {
        return rightCount - leftCount;
      }
      return leftName.localeCompare(rightName);
    },
  );

  const lines = ["- Component rerender count:"];
  sorted.forEach(([componentName, count], index) => {
    lines.push(`  ${index + 1}. ${componentName} — ${count}`);
  });
  return lines;
}
