// Generated by an LLM and not yet reviewed by a human.
import type { CommittedFiberChange } from "@react-record/devtools-api";

import { formatDurationMsInline } from "../utils/format-duration";

export type ComponentTimingEntry = {
  actualMs: number | null;
  componentName: string;
  selfMs: number | null;
};

export type CommitTimingSummary = {
  commitIndex: number;
  entries: ComponentTimingEntry[];
  hasTimingData: boolean;
  totalActualMs: number | null;
  totalSelfMs: number | null;
};

export type PaintTimingSummary = {
  commitCount: number;
  commitsWithTimingCount: number;
  paintNumber: number;
  perCommitActualMs: Array<number | null>;
  startCommitIndex: number;
  endCommitIndex: number;
  topComponents: ComponentTimingEntry[];
  totalActualMs: number | null;
  totalSelfMs: number | null;
};

const TOP_COMPONENT_LIMIT = 3;

function aggregateComponentTimings(
  commitChanges: CommittedFiberChange[],
): Map<string, { actualMs: number | null; selfMs: number | null }> {
  const byComponent = new Map<string, { actualMs: number | null; selfMs: number | null }>();

  for (const change of commitChanges) {
    const componentName = change.displayName;
    if (componentName == null) {
      continue;
    }

    const existing = byComponent.get(componentName) ?? { actualMs: null, selfMs: null };

    if (change.actualDuration != null) {
      existing.actualMs = (existing.actualMs ?? 0) + change.actualDuration;
    }
    if (change.selfDuration != null) {
      existing.selfMs = (existing.selfMs ?? 0) + change.selfDuration;
    }

    byComponent.set(componentName, existing);
  }

  return byComponent;
}

function compareTimingEntries(left: ComponentTimingEntry, right: ComponentTimingEntry): number {
  const leftActual = left.actualMs ?? -1;
  const rightActual = right.actualMs ?? -1;
  if (leftActual !== rightActual) {
    return rightActual - leftActual;
  }

  const leftSelf = left.selfMs ?? -1;
  const rightSelf = right.selfMs ?? -1;
  if (leftSelf !== rightSelf) {
    return rightSelf - leftSelf;
  }

  return left.componentName.localeCompare(right.componentName);
}

export function buildCommitTimingSummaries(
  fiberChangesByCommit: CommittedFiberChange[][],
): CommitTimingSummary[] {
  return fiberChangesByCommit.map((commitChanges, commitIndex) => {
    const byComponent = aggregateComponentTimings(commitChanges);

    let totalActualMs: number | null = null;
    let totalSelfMs: number | null = null;
    let hasTimingData = false;

    const entries: ComponentTimingEntry[] = [];

    for (const [componentName, { actualMs, selfMs }] of byComponent) {
      entries.push({ actualMs, componentName, selfMs });

      if (actualMs != null) {
        totalActualMs = (totalActualMs ?? 0) + actualMs;
        hasTimingData = true;
      }
      if (selfMs != null) {
        totalSelfMs = (totalSelfMs ?? 0) + selfMs;
        hasTimingData = true;
      }
    }

    entries.sort(compareTimingEntries);

    return {
      commitIndex,
      entries,
      hasTimingData,
      totalActualMs,
      totalSelfMs,
    };
  });
}

type BuildPaintTimingSummariesInput = {
  commitTimingSummaries: CommitTimingSummary[];
  paintCommitIndices: number[];
};

export function buildPaintTimingSummaries({
  commitTimingSummaries,
  paintCommitIndices,
}: BuildPaintTimingSummariesInput): PaintTimingSummary[] {
  const commitLimit = commitTimingSummaries.length;
  if (paintCommitIndices.length === 0 && commitLimit === 0) {
    return [];
  }

  const summaries: PaintTimingSummary[] = [];
  let startCommitIndex = 0;

  const pushSegment = (paintNumber: number, start: number, end: number) => {
    const segmentCommits = commitTimingSummaries.slice(start, end + 1);
    const perComponent = new Map<string, { actualMs: number | null; selfMs: number | null }>();
    let totalActualMs: number | null = null;
    let totalSelfMs: number | null = null;
    let commitsWithTimingCount = 0;
    const perCommitActualMs: Array<number | null> = [];

    for (const commit of segmentCommits) {
      perCommitActualMs.push(commit.totalActualMs);
      if (commit.hasTimingData) {
        commitsWithTimingCount += 1;
      }
      if (commit.totalActualMs != null) {
        totalActualMs = (totalActualMs ?? 0) + commit.totalActualMs;
      }
      if (commit.totalSelfMs != null) {
        totalSelfMs = (totalSelfMs ?? 0) + commit.totalSelfMs;
      }

      for (const entry of commit.entries) {
        const existing = perComponent.get(entry.componentName) ?? {
          actualMs: null,
          selfMs: null,
        };
        if (entry.actualMs != null) {
          existing.actualMs = (existing.actualMs ?? 0) + entry.actualMs;
        }
        if (entry.selfMs != null) {
          existing.selfMs = (existing.selfMs ?? 0) + entry.selfMs;
        }
        perComponent.set(entry.componentName, existing);
      }
    }

    const topComponents: ComponentTimingEntry[] = Array.from(perComponent.entries())
      .map(([componentName, { actualMs, selfMs }]) => ({
        actualMs,
        componentName,
        selfMs,
      }))
      .sort(compareTimingEntries)
      .slice(0, TOP_COMPONENT_LIMIT);

    summaries.push({
      commitCount: segmentCommits.length,
      commitsWithTimingCount,
      endCommitIndex: end,
      paintNumber,
      perCommitActualMs,
      startCommitIndex: start,
      topComponents,
      totalActualMs,
      totalSelfMs,
    });
  };

  paintCommitIndices.forEach((paintCommitIndex, paintIndex) => {
    pushSegment(paintIndex + 1, startCommitIndex, paintCommitIndex);
    startCommitIndex = paintCommitIndex + 1;
  });

  if (startCommitIndex < commitLimit) {
    pushSegment(paintCommitIndices.length + 1, startCommitIndex, commitLimit - 1);
  }

  return summaries;
}

const SUMMARY_TOP_COMPONENT_LIMIT = 3;

export function buildTimingSummaryLines(commitTimingSummaries: CommitTimingSummary[]): string[] {
  const commitsWithTiming = commitTimingSummaries.filter((summary) => summary.hasTimingData);
  if (commitsWithTiming.length === 0) {
    return [];
  }

  let totalActualMs: number | null = null;
  let totalSelfMs: number | null = null;
  const actualByComponent = new Map<string, number>();

  for (const summary of commitsWithTiming) {
    if (summary.totalActualMs != null) {
      totalActualMs = (totalActualMs ?? 0) + summary.totalActualMs;
    }
    if (summary.totalSelfMs != null) {
      totalSelfMs = (totalSelfMs ?? 0) + summary.totalSelfMs;
    }
    for (const entry of summary.entries) {
      if (entry.actualMs == null) {
        continue;
      }
      actualByComponent.set(
        entry.componentName,
        (actualByComponent.get(entry.componentName) ?? 0) + entry.actualMs,
      );
    }
  }

  const topComponents = Array.from(actualByComponent.entries())
    .sort(([leftName, leftMs], [rightName, rightMs]) => {
      if (rightMs !== leftMs) {
        return rightMs - leftMs;
      }
      return leftName.localeCompare(rightName);
    })
    .slice(0, SUMMARY_TOP_COMPONENT_LIMIT);

  const lines = [
    `- Total render time: ${formatDurationMsInline(totalActualMs)} (self ${formatDurationMsInline(totalSelfMs)}) across ${commitsWithTiming.length} commit(s)`,
  ];

  if (topComponents.length > 0) {
    lines.push("- Top components by render time:");
    topComponents.forEach(([name, ms], index) => {
      lines.push(`  ${index + 1}. ${name} — ${formatDurationMsInline(ms)}`);
    });
  }

  return lines;
}

export function buildPaintTimingSummaryLines(summary: PaintTimingSummary): string[] {
  if (summary.totalActualMs == null && summary.topComponents.length === 0) {
    return [];
  }

  const lines = [
    `- Total render time: ${formatDurationMsInline(summary.totalActualMs)} (self ${formatDurationMsInline(summary.totalSelfMs)}) across ${summary.commitCount} commit(s)`,
  ];

  const meaningfulTop = summary.topComponents.filter(({ actualMs }) => actualMs != null);
  if (meaningfulTop.length > 0) {
    lines.push("- Top components by render time:");
    meaningfulTop.forEach(({ componentName, actualMs }, index) => {
      lines.push(`  ${index + 1}. ${componentName} — ${formatDurationMsInline(actualMs)}`);
    });
  }

  return lines;
}
